[package]
name = "encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
arith = { path = "../../../../arith" }
serdes = { path = "../../../../serdes" }

rand.workspace = true
ethnum.workspace = true
ark-std.workspace = true
thiserror.workspace = true
itertools.workspace = true
derivative.workspace = true
